INSERT INTO Theme (nom) VALUES ("Sport");
INSERT INTO Theme (nom, idNomPere) SELECT "Football", id From Theme where nom="Sport";
INSERT INTO Theme (nom, idNomPere) SELECT "Rugby", id From Theme where nom="Sport";
INSERT INTO Theme (nom, idNomPere) SELECT "Natation", id From Theme where nom="Sport";
INSERT INTO Theme (nom, idNomPere) SELECT "Handball", id From Theme where nom="Sport";
INSERT INTO Theme (nom, idNomPere) SELECT "Equitation", id From Theme where nom="Sport";
INSERT INTO Theme (nom, idNomPere) SELECT "Ski", id From Theme where nom="Sport";
INSERT INTO Theme (nom, idNomPere) SELECT "Golf", id From Theme where nom="Sport";
INSERT INTO Theme (nom, idNomPere) SELECT "Petanque", id From Theme where nom="Sport";



INSERT INTO Theme (nom) VALUES ("Musique");
INSERT INTO Theme (nom, idNomPere) SELECT "Latino-Americaine", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Hip-hop", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Pop", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Asiatique", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Trap", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Country", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Electro", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Reggae", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "R&B", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Rock", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Soul", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Classique", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Pop Rock", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Rock alternatif", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Hard Rock", id From Theme where nom="Musique";
INSERT INTO Theme (nom, idNomPere) SELECT "Heavy Metal", id From Theme where nom="Musique";


INSERT INTO Theme (nom) VALUES ("Film");
INSERT INTO Theme (nom, idNomPere) SELECT "Action", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Animation", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Arts Martiaux", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Aventure", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Biopic", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Bollywood", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Classique", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Comédie", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Comédie dramatique", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Comédie musicale", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Dessin animé", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Documentaire", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Drame", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Epouvante-horreur", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Erotique", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Espionnage", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Famille", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Fantastique", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Guerre", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Historique", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Judiciaire", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Péplum", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Policier", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Romance", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Science fiction", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Show", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Thriller", id From Theme where nom="Film";
INSERT INTO Theme (nom, idNomPere) SELECT "Western", id From Theme where nom="Film";

INSERT INTO Theme (nom) VALUES ("Livre");
INSERT INTO Theme (nom, idNomPere) SELECT "Policier", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Terroir", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Sentimental", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Biographie", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Science-fiction", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Erotique", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Historique", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Conte", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Poesie", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Theatre", id From Theme where nom="Livre";
INSERT INTO Theme (nom, idNomPere) SELECT "Nouvelle", id From Theme where nom="Livre";


INSERT INTO Theme (nom) VALUES ("Animaux");


INSERT INTO Theme (nom) VALUES ("DomaineMetier");

INSERT INTO Theme (nom, idNomPere) SELECT "Avocats", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Coiffeur", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Agent immobilier", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Banques", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Psychologue", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Assurances agents géneraux", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Agent general assurance", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Ostéopathe", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Architecte", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Pédiatre", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Restaurants", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Hôtel", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecins néphrologie", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Expert comptable", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Syndic de copropriété", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Neurologue", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Psychanalyste", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Psychothérapeute", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Chirurgien orthopédiste", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Promoteur immobilier", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Opticien", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Institut de beauté", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Maintenance informatique", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Audioprothésiste", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Entreprises de nettoyage", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Carrosserie automobile", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Société nettoyage", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Entreprise nettoyage", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Bijouterie", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Kinésithérapeute", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Service informatique", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Location automobiles", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Auto-école", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Masseurs kinésithérapeutes", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Administrateur de biens", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Formation professionnelle", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Centres de radiologie", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Agence intérim", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Vêtements femmes", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Services à domicile", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Ophtalmologiste", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecine interne", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Architectes d'intérieur", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Hypnothérapeute", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Taxi", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Dépannage plomberie", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecins généralistes", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecins neurochirurgie", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Pharmacie", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Entreprise peinture", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Radiologue", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecins gériatrie", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Diagnostic immobilier", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Fast food", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Contrôle technique de véhicules", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecin biologiste", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Gestion locative", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Garage automobile", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Cardiologue", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecine nucléaire", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Garages automobiles réparation", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Crédit immobilier", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Médecins chirurgie cardio vasculaire et thoracique", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Diabétologue", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Associations humanitaires d'entraide sociales", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Électricité générale", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Avocat droit du travail", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Gastro entérologue", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Avocat droit des personnes", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Chirurgien", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Avocat droit famille", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Ambulances", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Agence de voyage", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Auto-écoles", id From Theme where nom="DomaineMetier";
INSERT INTO Theme (nom, idNomPere) SELECT "Gestion de patrimoine", id From Theme where nom="DomaineMetier";
